<div>
<?php Portal::send('title', 'Wizytówki internetowe') ?>
<?php Portal::send('metaTags', 'Przykładowa strona') ?>
</div>

<div class="article rounded-lg">  
	<div class="p-6">
		<h1 id="pages_home_1" class="cmsText">Wizytówki internetowa<br>
</h1>
		<p id="pages_home_2" class="cmsText">
			Witaj na naszej stronie internetowej!<br>
			Jest to przykładowa strona, która może być dostosowana do Państwa potrzeb.<br><br>
			Prosta strona internetowa - wizytówka.<br>
			Można zakupić taką stronę - zmieniam teksty, zdjęcia, wprowadzam Państwa dane.<br>
			Stronę można obejrzeć klikając w poszczególne zakładki. Jest to gotowa przykładowa strona internetowa.<br>
			Strona nie jest oparta o popularne CMSy dzięki temu jest bardzo szybka w pobieraniu co jest istotne dla działań SEO.<br>  
		</p>

	</div>
</div>