<style>

.alert {
  display: none;	
  padding: 8px;
  border-radius: 4px;
  border: 2px solid transparent;
  margin: 0px  0px 10px 0px;
}
.alert-danger {
  display: block;
  color: #a94442;
  background-color: #f2dede;
  border-color: #ebccd1;
}

.alert-warning {
  display: block;
  color: #8a6d3b;
  background-color: #fcf8e3;
  border-color: #faebcc;
}

.alert-success {
  display: block;
  color: #3c763d;
  background-color: #dff0d8;
  border-color: #d6e9c6;
}

.map-responsive{
    overflow:hidden;
    padding-bottom:60%;
    position:relative;
    height:0;
}
.map-responsive iframe{
    left:0;
    top:0;
    height:100%;
    width:100%;
    position:absolute;

}


</style>





<div class="article rounded-lg">  
	<div class="p-6">
<h1 id="pages_kontakt_1" class="cmsText">Kontakt</h1>

<div class="mt-10 grid grid-cols-6">
   	<div class="col-span-3">
       	<div class="table w-full leading-5">
  				<div class="table-row-group">
			  		<div class="table-row">
      				<div class="table-cell pl-5 py-2 font-bold"><svg class="pt-1" xmlns="http://www.w3.org/2000/svg" height="20" viewbox="0 0 24 24" width="20"><path d="M0 0h24v24H0z" fill="none"></path><path d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4l-8 5-8-5V6l8 5 8-5v2z"></path></svg></div>
      				<div class="table-cell py-2"><a id="pages_kontakt_2" class="cmsText hover:text-gray-400" href="mailto: mxseba80@gmail.com">mxseba80@gmail.com</a></div>
					</div>
					<div class="table-row">
      				<div class="table-cell pl-5 py-2 font-bold"><svg class="pt-1" xmlns="http://www.w3.org/2000/svg" height="20" viewbox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"></path><path d="M6.62 10.79c1.44 2.83 3.76 5.14 6.59 6.59l2.2-2.2c.27-.27.67-.36 1.02-.24 1.12.37 2.33.57 3.57.57.55 0 1 .45 1 1V20c0 .55-.45 1-1 1-9.39 0-17-7.61-17-17 0-.55.45-1 1-1h3.5c.55 0 1 .45 1 1 0 1.25.2 2.45.57 3.57.11.35.03.74-.25 1.02l-2.2 2.2z"></path></svg></div>
      				<div class="table-cell py-2"><a id="pages_kontakt_3" class="cmsText no-underline" href="tel:+48516486390">516 486 390</a></div>
					</div>
			 
					<div class="table-row">
      				<div class="table-cell pl-5 py-2 font-bold"><svg class="pt-1" xmlns="http://www.w3.org/2000/svg" height="20" viewbox="0 0 24 24" width="24"><path d="M0 0h24v24H0z" fill="none"></path><path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"></path></svg></div>
      				<div id="pages_kontakt_4" class="cmsText table-cell py-2">ul. Sienkiewicza 15<br>85-037 Bydgoszcz</div>
      			</div>
    			
				</div>
			</div>




	</div>
	<div class="col-span-1">
		<img onerror="placeholder(this,80,80)" class="cmsImage" src="/themes/assets/images/site/contact.webp" alt="Mail">   
	</div>
</div>  
    
	
<span class="text-lg">Lokalizacja:</span>


<div class="mt-1 map-responsive">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2846.824174524805!2d17.99744100099132!3d53.1302235026414!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x470313c78ad58485:0xca0e5c26ca36ae76!2sHenryka Sienkiewicza 15, 85-011 Bydgoszcz!5e0!3m2!1spl!2spl!4v1613043830870!5m2!1spl!2spl" width="400" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
	</iframe>
</div>
	
<br>
<br>




<div class=" m-auto w-4/5 px-10">
  
  
<p id="pages_kontakt_5" class="cmsText text-lg mb-6">Nie znalazłeś wszystkich informacji na naszej stronie ? Zapytaj:</p>
<form class="md:max-w-sm mb-5" action="javascript:void(0);" method="POST" novalidate="novalidate" id="messageForm" onsubmit="return sendMessage(this);">
	<div class="mb-6">
    	<label class="block text-gray-800 font-semibold text-sm mb-1" for="email">
	  		Twój email (wymagane)
      	</label>
    	<input type="email" name="email" class="bg-gray-100 appearance-none border-2 border-gray-400 rounded w-full p-1 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-gray-400" id="email">
    </div>



  	<div class="mb-6">
    	<label class="block text-gray-800 font-semibold text-sm mb-1" for="subject">
			Temat
    	</label>
        <input type="text" name="subject" class="bg-gray-100 appearance-none border-2 border-gray-400 rounded w-full p-1 text-gray-700 leading-tight focus:outline-none focus:bg-white focus:border-gray-400" id="subject">
	</div>
	
	<div class="mb-6">
		<label class="block text-gray-800 font-semibold text-sm mb-1" for="message">
			Treść wiadomości
		</label>	
		<textarea name="message" cols="50" rows="10" class="bg-gray-100 appearance-none border-2 border-gray-400 rounded  w-full p-1 leading-tight focus:outline-none  focus:bg-white  focus:border-gray-400" id="message">
		</textarea>
	</div>
	<!--
	<button type="submit" class="shadow bg-red-700 hover:bg-red-400  focus:outline-none text-white py-1 px-3 rounded">
    	Wyślij
    </button>
	-->
	<button id="btnSend" type="submit" class="inline-flex items-center py-1 px-3 border border-transparent  leading-6 rounded text-white bg-red-700 hover:bg-red-600 active:bg-red-800 focus:outline-none transition ease-in-out duration-150">
    	<svg class="hidden animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24">
    		<circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
    		<path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
    	</svg>
        Wyślij
    </button>
   
</form>


<div id="alertWarning" class="hidden text-base mb-8 md:mr-20 bg-yellow-100 border-l-4 border-yellow-500  text-yellow-700 p-4" role="alert">
</div>

<div id="alertDanger" class="hidden  text-base mb-8 md:mr-20 bg-red-100 border-l-4 border-red-500 text-red-700 p-4" role="alert">
</div>

<div id="alertSuccess" class="hidden text-base mb-8 md:mr-20 bg-green-100 border-l-4 border-green-500 text-green-700 p-4" role="alert">
</div>
<a class="hover:text-gray-500 text-xs" href="/polityka-prywatnosci">Polityka prywatności</a>
</div> <!-- e-mail form -->
</div>






</div>


<script type="text/javascript">
reset();





function sendMessage(oFormElement){
	let btnSend = document.getElementById("btnSend");
	btnSend.disabled = true;
	btnSend.classList.add("cursor-not-allowed");
	document.querySelector('#btnSend svg').classList.remove("hidden");
	
	var xhttp = new XMLHttpRequest();
	xhttp.onreadystatechange = function() {
		if(this.readyState == 4){
			response(this);
		}
	};
	let formData = new FormData(oFormElement);
	message = formData.get('message')
	message = message.replace(/\n/g,'<br/>');
	formData.set('message', message);
	
	 
	xhttp.open("POST", "/email/?param=email", true);
	xhttp.send(formData);
	return false;
}



function response(e){
	
	let btnSend = document.getElementById("btnSend");
	btnSend.disabled = false;
	btnSend.classList.remove("cursor-not-allowed");
	document.querySelector('#btnSend svg').classList.add("hidden");
	
	let alertDanger = document.getElementById("alertDanger");
	let alertWarning = document.getElementById("alertWarning");
	let alertSuccess = document.getElementById("alertSuccess");

	alertDanger.classList.add("hidden"); 
	alertWarning.classList.add("hidden");
	alertSuccess.classList.add("hidden");
	
	if (e.status == 200) {
		
		const obj = JSON.parse(e.responseText);
		if('error' in obj){
			alertWarning.classList.remove("hidden");
			alertWarning.innerHTML =  obj.error.msg;
		} 
		if('data' in obj && obj.data == "OK"){
			alertSuccess.classList.remove("hidden"); 
			alertSuccess.innerHTML = 'Twoja wiadomość została wysłana. Dziękujemy!';
		}
			reset();
	} else {
		alertDanger.classList.remove("hidden"); 
		alertDanger.innerHTML = "Błąd servera.";
	}
}


function reset(){
	document.getElementById("email").value = "";
	document.getElementById("subject").value = "";
	document.getElementById("message").value = "";
}
</script>