<div>
<?PHP Portal::send('title', 'Oferta - wizytówki internetowe') ?>
<?PHP Portal::send('metaTags', 'Przykładowa podstrona') ?>
</div>




<style>
ul.offer {
	position: relative;
	list-style: none;
	margin-left: 0.8em;
	padding-left: 1.2em;

}
ul.offer li:before {
	content: "✔";
	position: absolute;
	left: 0;
	color: darkcyan;
}
</style>


<div class="article rounded-lg">  
	<div class="p-6">
		<h1 id="pages_oferta_1" class="cmsText">Oferta<br>
</h1>
		<p id="pages_oferta_2" class="cmsText">
			Zajmuję się tworzeniem prostych gotowych stron internetowych.
			Skorzystanie z mojej usług jest łatwe - wystarczy wysłać teksty, zdjęcia i oczekiwania wobec strony, np. e-mailem.<br>
			Modyfikuję teksty i zdjęcia, zmieniam szatę graficzną, dostosowuję stronę do Państwa oczekiwań.
			Jeżeli posiadacie Państwo swój adres internetowy mogę podpiąć stronę pod adres istniejący, jeżeli nie - możemy zarejestrować nowy adres, o ile tylko nazwa nie jest już przez kogoś zarezerwowana.
			W 90% przypadków pracuję zdalnie, wysyłam klientowi lik do strony w czasie jej tworzenia i na bieżąco konsultujemy co i jak ma wyglądać.
			W większości przypadków spotkanie nie jest konieczne.
			Szata graficzna strony i jej wygląd jest do korekty zgodnie z oczekiwaniami klienta.<br><br>
			Koszt strony 250zł - cena zawiera:<br>
			</p>
<ul id="pages_oferta_3" class="cmsText offer">
	
		Dostarczenie drogą elektroniczną kompletnej strony ze zmianami treści (tekst i zdjęcia).
	
	
		1 rok utrzymania strony na naszym serwerze (hosting) z certyfikatem SSL. Możliwość przedłużenia na kolejne lata.
	
	
		Zgodnie z wymogami SEO: Zoptymalizowany tytuł, przyjazne adresy<br>
</ul>
		
	</div>
</div>