<!DOCTYPE html>
<html lang="pl">

<head>
	<title>Panel logowania</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	<link rel="stylesheet" href="/themes/assets/css/loginPanel.css">
	<link rel="icon" type="image/png" href="/favicon.png">
	
	<script src="https://kit.fontawesome.com/a81368914c.js"></script>
  
</head>

<body class="bg-gray-300">
    <div class="w-full h-screen flex items-center justify-center">
        <form action="/adminLog/?a=login" method="post" class="w-full md:w-1/3 bg-white rounded-lg">
            <div class="flex font-bold justify-center mt-6">
                <img class="h-20 w-20" src="/themes/assets/images/site/avatar.png">
            </div>
            <h2 class="text-3xl text-center text-gray-700 mb-4">Panel logowania</h2>
            <div class="px-12 pb-10">
                <div class="w-full mb-2">
                    <div class="flex items-center">
                        <i class='ml-3 fill-current text-gray-600 text-xs z-10 fa fa-user'></i>
                        <input name="login" type='text' placeholder="Nazwa użytkownika"
                            class="border-gray-400 focus:border-green-700 -mx-6 px-8  w-full border rounded py-2 text-gray-700 focus:outline-none" />
                    </div>
                </div>
                <div class="w-full mb-2">
                    <div class="flex items-center">
                        <i class='ml-3 fill-current text-gray-600 text-xs z-10 fa fa-lock'></i>
                        <input name="password" type='password' placeholder="Hasło"
                            class="border-gray-400 focus:border-green-700 -mx-6 px-8 w-full border rounded py-2 text-gray-700 focus:outline-none" />
                    </div>
                </div>
                <a href="#" class="text-xs text-gray-600 float-right mb-4">Zapomniałeś hasła?</a>
                <button type="submit"
                    class="w-full py-2 rounded-full bg-green-600 text-gray-100 hover:bg-green-500 active:bg-green-800 focus:outline-none transition ease-in-out duration-150">Loguj</button>
				
        </form>
    </div>
</body>

</html>