<?PHP Portal::send('title', 'Polityka prywatności') ?><div class="article rounded-lg">  
	<div class="p-6">
   <h2 id="pages_polityka-prywatnosci_1" class="cmsText selectEdit">Polityka prywatności</h2>
<p id="pages_polityka-prywatnosci_2" class="text-base cmsText selectEdit">
Administratorem Twoich danych jest [nazwa firmy] z siedzibą w [miejscowość] przy ul. [ulica], wpisanej do Centralnej Ewidencji i Informacji o Działalności Gospodarczej, pod numerem NIP: [nip firmy], REGON: [regon].<br>
W sprawach związanych z przetwarzaniem i ochroną danych osobowych wyznaczony został
punkt kontaktowy w postaci adresu e-mail: [e-mail formularza kontaktowego].<br>
Kontakt we wskazanych sprawach możliwy jest także w postaci tradycyjnej korespondencji na adres administratora z dopiskiem: „Ochrona Danych Osobowych” oraz osobiście pod adresem [adres firmy].<br>

Podane przez Ciebie dane osobowe będą przetwarzane w następujących celach:<br>
– wykonania umowy kupna-sprzedaży bądź usługi – przetwarzanie jest niezbędne do wykonania umowy, aż do czasu zakończenia umowy,<br>
– marketingu bezpośredniego – do czasu zakończenia umowy lub złożenia sprzeciwu,<br>
– finansowo-księgowych – przetwarzanie jest niezbędne do wykonania przepisów prawa podatkowego,<br>
– obrony przed roszczeniami i dochodzenia roszczeń – do czasu wygaśnięcia okresu roszczeń zgodnie z przepisami Kodeksu Cywilnego,<br>
– prowadzenia procesów reklamacyjnych.<br>

Posiadasz prawo dostępu do treści swoich danych oraz prawo ich sprostowania, usunięcia, ograniczenia przetwarzania, prawo do przenoszenia danych, prawo wniesienia sprzeciwu (np. jeśli dane są przetwarzane na podstawie Twojej zgody lub w celach marketingowych czy udostępniania Twoich danych);
posiadasz prawo do cofnięcia zgody w dowolnym momencie. W celu cofnięcia zgody możesz skontaktować się z punktem obsługi klienta w naszej siedzibie bądź biurze [adres firmy] lub wysyłając wiadomość e-mail na adres: [adres e-mail].<br>
Masz również prawo wniesienia skargi do organu nadzorczego – Prezesa Urzędu Ochrony Danych Osobowych.

Podanie przez Ciebie danych osobowych jest w pełni dobrowolne. Niepodanie danych osobowych będzie skutkowało niemożliwością pełnego wykonania zobowiązań, przyjętych przez [nazwa firmy] w ramach zawieranych z Tobą umów.
</p>

</div>
</div>