<head>
<style>
.banner {
  background-color: #FFFFFFaF;
}

.banner .content {
  padding: 5px 0 10px 10px;
} 

.text_shadow {
  color: rgb(111, 214, 240);
  font-size: 35px;
  font-weight: 700;
  text-shadow: rgb(20, 35, 36) -3px 3px 7px;
  line-height: 1.2;
}
</style>

</head>
<div class="banner" role="banner">
  <div class="row">
  		<div class="content">
        <div id="components_header_1" class="text_shadow cmsText">Wizytówka<br></div>
</div>
  </div>
</div>