<style>
#menu {
	background: linear-gradient(to bottom,  #000000,  #3D3D3D);
	color: #FFF;
	height: 40px;
	padding-left: 18px;
	border-radius: 0px;
	z-index: 10;
}
#menu ul, #menu li {
	margin: 0 auto;
	padding: 0;
	list-style: none
}

#menu li {
	float: left;
	display: inline;
	position: relative;
}
#menu a {
	display: block;
	line-height: 40px;
	padding: 0 14px;
	text-decoration: none;
	color: #FFFFFF;
	font-size: 16px;
}
#menu a.dropdown-arrow:after {
	content: "\25BE";
	margin-left: 5px;
}
#menu li a:hover {
	color: #FFFFFF;
	background: #AA3F0A;
}
#menu input {
	display: none;
	margin: 0;
	padding: 0;
	height: 40px;
	width: 100%;
	opacity: 0;
	cursor: pointer
}
#menu label {
	display: none;
	line-height: 40px;
	text-align: center;
	position: absolute;
	left: 35px
}
#menu label:before {
	font-size: 1.6em;
	content: "\2261"; 
	margin-left: 20px;
}
#menu ul.sub-menus{
	height: auto;
	overflow: hidden;
	width: 210px;
	background: #FFFFFF;
	position: absolute;
	z-index: 99;
	display: none;
	box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
}
#menu ul.sub-menus li {
	display: block;
	width: 100%;

}
#menu ul.sub-menus a {
	color: #2E2E2E;
	font-size: 15px;
}
#menu li:hover ul.sub-menus {
	display: block
}
#menu ul.sub-menus a:hover{
	background: #C2C2C2;
	color: #000000;
}

#menu .active {
  color: #FFFFFF;
  background: #A0B33B !important;
}

@media screen and (max-width: 768px){
	#menu {position:relative}
	#menu ul {background:#111;position:absolute;top:100%;right:0;left:0;z-index:3;height:auto;display:none}
	#menu ul.sub-menus {width:100%;position:static;}
	#menu ul.sub-menus a {padding-left:30px;}
	#menu li {display:block;float:none;width:auto;}
	#menu input, #menu label {position:absolute;top:0;left:0;display:block}
	#menu input {z-index:4}
	#menu input:checked + label {color:white}
	#menu input:checked + label:before {content:"\00d7"}
	#menu input:checked ~ ul {display:block}
}

/*
.sticky {
	position: fixed;
	top: 0;
	width: 100%;
	-webkit-box-shadow: 0px 0px 8px 1px rgba(0,0,0,0.86); 
	box-shadow: 0px 0px 8px 1px rgba(0,0,0,0.86);
}

*/

</style>


<nav id="menu">
<div class="row">
	<input type="checkbox" id="responsive-menu" onclick="updatemenu()"><label></label>
	<ul>
   	<li><a id="components_navbar_1" class="cmsText" href="/">Strona główna</a></li>
   	<li><a id="components_navbar_2" class="cmsText" href="/oferta/">Oferta</a></li>
   	<li><a id="components_navbar_3" class="cmsText" href="/galeria/">Galeria</a></li>
		<li><a id="components_navbar_4" class="cmsText" href="/kontakt/">Kontakt</a></li>
	</ul>


</div>
</nav>


<script>
/*
window.onscroll = function() {myFunction()};
var navbar = document.getElementById("menu");
var sticky = navbar.offsetTop;

  
function myFunction() {
	
	if (window.pageYOffset >= sticky) {
		navbar.classList.add("sticky")
	} else {
		navbar.classList.remove("sticky");
	}
}
*/

let page = document.querySelectorAll('#menu > div > ul > li > a');

page.forEach(function(a, index){
	
	//console.log(a.classList.contains('selectEdit'));

	<?php if (!empty($_SESSION['user'])) : ?>
		a.setAttribute("title", "Wejście w podstronę: Prawy klawisz ALT i przycisk myszy"); 
	<?php endif; ?>

	if(a.getAttribute('href') == window.location.pathname){
		page[index].classList.add('active');
	}
}); 




page = document.querySelectorAll('#menu .sub-menus a');
page.forEach(function(a){
	if(a.getAttribute('href') == window.location.pathname){
		let b = document.querySelectorAll('#menu  a');
		b[1].classList.add('active');
	}
})


function updatemenu() {
	if (document.getElementById('responsive-menu').checked == true) {
		document.getElementById('menu').style.borderBottomRightRadius = '0';
		document.getElementById('menu').style.borderBottomLeftRadius = '0';
	} else {
		document.getElementById('menu').style.borderRadius = '0px';
	}
}
</script>